### ISSUE TITLE
Unable to compile the downloaded code in VS2013 and .net 4.5

### ISSUE THREAD

**Issue by sohailrazaqau** [SavchukSergey/DnsZone#2]
Hello there,

When compiling the downloaded source, i get some errors like the following at many places in the code;
Error	1	Unexpected character '$'	\DnsZone\DnsZoneFile.cs
Error	2	Invalid token ';' in class, struct, or interface member declaration	\DnsZone\Records\SrvResourceRecord.cs

and, at the following line it says, unexpected token and that it cannot resolve "count" etc.
 public bool IsEof => Tokens.Count == 0;

also, in some classes it says that the class does not implement the abstract members etc.

Can you please guide me how to compile this code? or if i need any prerequisites?

I am using Visual Studio 2013 with .net framework 4.6

many thanks.

**Comment by SavchukSergey** [comment]
Hello

'$' character is string interpolation introduced in c# 6.0.
I`m compiling using Visual Studio 2017. I think Visual Studio 2015 will be enough.

If you don't want to install VS2015+ you can use compiled binaries from nuget 

Best Regards,
Sergey Savchuk
